# Generated by Django 2.2.2 on 2019-07-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudApplication', '0004_auto_20190703_0040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Donor',
        ),
        migrations.AlterModelTable(
            name='donor',
            table='donor',
        ),
    ]
