# Generated by Django 2.2.2 on 2019-07-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudApplication', '0005_auto_20190703_0105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donor',
            new_name='Employee',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
