# Generated by Django 2.2.2 on 2019-07-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudApplication', '0006_auto_20190703_0114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
