# Generated by Django 2.2.2 on 2019-07-03 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudApplication', '0007_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('serial_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crudApplication.Recipient')),
                ('whole_blood_unit', models.CharField(max_length=3)),
                ('whole_blood_rate_per_unit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('whole_blood_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('crossmatch_blood_unit', models.CharField(max_length=3)),
                ('crossmatch_blood_rate_per_unit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('crossmatch_blood_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('signature', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Charge',
            },
        ),
    ]
