# Generated by Django 2.2.2 on 2019-07-04 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudApplication', '0013_auto_20190704_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('reg_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crudApplication.Donor')),
                ('disease_before_how_longdays', models.IntegerField(max_length=8)),
                ('lever_disease', models.BooleanField()),
                ('Asphyxia', models.BooleanField()),
                ('cough', models.BooleanField()),
                ('heart_disease', models.BooleanField()),
                ('malaria', models.BooleanField()),
                ('kalaazar', models.BooleanField()),
                ('typhoid', models.BooleanField()),
                ('operation_in_three_month', models.BooleanField()),
                ('any_treatment_medicine_now', models.BooleanField()),
                ('gestric', models.BooleanField()),
                ('Haematemeses', models.BooleanField()),
                ('blood_loo', models.BooleanField()),
                ('rheumatic_fever', models.BooleanField()),
                ('diabetes', models.BooleanField()),
                ('epilepsy', models.BooleanField()),
                ('kidney_disease', models.BooleanField()),
                ('social_disease', models.BooleanField()),
                ('skin_disease', models.BooleanField()),
                ('is_blood_taken', models.BooleanField()),
                ('is_vaccine_taken', models.BooleanField()),
            ],
            options={
                'db_table': 'medical_history',
            },
        ),
    ]
