# Generated by Django 2.2.2 on 2019-07-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudApplication', '0014_medicalhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='reg_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crudApplication.Donor'),
        ),
    ]
